add Email on yellow pages and update fields of yellow pages entities.
NiteshTuladhar/ronb-node pull request #1
Opened 2023-02-01 04:40 UTC by Grunze1s

Create yellowPagesEmail Entity and related with yellow pages with manytoone relation 
made is_emergency of YellowPagesPhoneNumber default to false 
made phone_number of YellowPagesPhoneNumber bigInt from Int 
add address field in YellowPagesAddress
made subsequent changes in resolver, dto, service, module

2023-02-01 09:31 UTC, shovan777 reviewed
Please review the feedback.

2023-02-01 09:31 UTC, shovan777 commented on src/schema.gql
> +  phone_number: Float
int why not???

2023-02-01 10:05 UTC, Grunze1s commented on src/schema.gql
> +  phone_number: Float
int only support 32 signed integer so to receive large we need float but bigint scalar is not provided by graphql so float is directly used by graphql schema which supports double precision floating point which is larger than int.
https://docs.nestjs.com/graphql/scalars

2023-02-01 10:05 UTC, Grunze1s commented on src/schema.gql
> +  phone_number: Float!
int only support 32 signed integer so to receive large we need float but bigint scalar is not provided by graphql so float is directly used by graphql schema which supports double precision floating point which is larger than int.
https://docs.nestjs.com/graphql/scalars

2023-02-01 10:06 UTC, Grunze1s commented on src/schema.gql
> +  phone_number: Float!
int only support 32 signed integer so to receive large we need float but bigint scalar is not provided by graphql so float is directly used by graphql schema which supports double precision floating point which is larger than int.
https://docs.nestjs.com/graphql/scalars

2023-02-01 10:07 UTC, Grunze1s commented
in future we might need to create custom saclar for bigint.

2023-02-02 03:56 UTC, shovan777 commented on src/schema.gql
> +  phone_number: Float!
Please use this [library](https://the-guild.dev/graphql/scalars/docs/scalars). It has most of the scalars we need. I think it is already included in packages.
https://the-guild.dev/graphql/scalars/docs/scalars/big-int

2023-02-02 03:57 UTC, shovan777 reviewed
Use [bigint](https://the-guild.dev/graphql/scalars/docs/scalars/big-int) for `BigInt` datatype like phonenumber

2023-02-02 03:58 UTC, shovan777 requested changes
Please make changes

2023-02-02 06:36 UTC, shovan777 approved these changes
Looks great :100:

2023-02-02 06:37 UTC, merged